custom:
  # Windows users should change this to ${env:USERNAME}
  user: ${env:USER}

service: ${self:custom.user}-aws-python

provider:
  name: aws
  runtime: python2.7

  environment:
    USERNAME: ${self:custom.user}

functions:
  hello:
    handler: handler.hello

package:
  exclude:
    - serverless/**
