custom:
  # Windows users should change this to ${env:USERNAME}
  user: ${env:USER}

service: ${self:custom.user}-aws-python

provider:
  name: aws
  runtime: python2.7

functions:
  hello:
    handler: handler.hello
