custom:
  user: ${env:USER}

service: ${self:custom.user}-aws-nodejs

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
    environment:
      TABLE_NAME: tableName2
    events:
      - http:
          path: hello
          method: get
