custom:
  # Windows users should change this to ${env:USERNAME}
  user: ${env:USER}

service: ${self:custom.user}-aws-nodejs

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
