service: ${env:USER}-aws-nodejs

provider:
  name: aws
  runtime: nodejs4.3

  environment:
    USERNAME: ${env:USER}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::my-text-messages-${env:USER}/*"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        - "arn:aws:sns:us-east-1:272016194640:dispatch-events-${env:USER}"
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
      Resource:
        - "arn:aws:dynamodb:us-east-1:272016194640:table/${env:USER}-character-counts"

functions:
  textmessagecreate:
    handler: handler.textmessagecreate
    events:
      - http:
          path: textmessage/create
          method: get
  textmessageprocess:
    handler: handler.textmessageprocess
    events:
      - sns: dispatch-events-${env:USER}

resources:
  Resources:
    CharacterCounts:
      Type: AWS::DynamoDB::Table
      Properties:
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "${env:USER}-character-counts"

    MyMessages:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-text-messages-${env:USER}
